amcl:
  ros__parameters:
    use_sim_time: false

    # 좌표계
    global_frame_id: map
    odom_frame_id: odom
    base_frame_id: base_link
    scan_topic: scan

    # 4WD 좌·우 차동 구동 로봇 모델
    robot_model_type: "nav2_amcl::DifferentialMotionModel"

    # Odometry 오차 모델
    alpha1: 0.2
    alpha2: 0.2
    alpha3: 0.2
    alpha4: 0.2
    alpha5: 0.2

    # Particle filter
    min_particles: 300
    max_particles: 1200
    pf_err: 0.05
    pf_z: 0.99
    resample_interval: 1

    # LiDAR 설정
    laser_model_type: "likelihood_field"
    laser_min_range: 0.1
    laser_max_range: 12.0
    laser_likelihood_max_dist: 2.0
    max_beams: 60

    # Laser probability model
    sigma_hit: 0.2
    lambda_short: 0.1
    z_hit: 0.5
    z_short: 0.05
    z_max: 0.05
    z_rand: 0.5

    # Beam skipping
    do_beamskip: false
    beam_skip_distance: 0.5
    beam_skip_threshold: 0.3
    beam_skip_error_threshold: 0.9

    # 위치 추정 갱신 조건
    update_min_d: 0.05
    update_min_a: 0.10

    # TF 및 pose
    tf_broadcast: true
    transform_tolerance: 1.0
    save_pose_rate: 0.5

    # 위치 추정 실패 시 particle 확산
    recovery_alpha_fast: 0.0
    recovery_alpha_slow: 0.0

    # 현재 검증용 초기 위치
    # 지도 생성 시작 위치와 동일한 위치에 로봇이 있다고 가정한다.
    set_initial_pose: true
    always_reset_initial_pose: false

    initial_pose:
      x: 0.0
      y: 0.0
      z: 0.0
      yaw: 0.0